plugins {
    alias(libs.plugins.multiplatform) apply false
    alias(libs.plugins.compose) apply false
    alias(libs.plugins.android.application) apply false
    alias(libs.plugins.android.library) apply false
    alias(libs.plugins.kotlin.android) apply false
    alias(libs.plugins.sqldelight) apply false
    alias(libs.plugins.kotlin.serialization) apply false
}

allprojects {
    task("compileJava").doLast {
        println("Dummy compileJava task:)")
    }
    task("testClasses").doLast {
        println("Dummy testClasses task:)")
    }
}

///*
// * This file was generated by the Gradle 'init' task.
// *
// * This is a general purpose Gradle build.
// * To learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.7/samples
// */

//
//val firstTask = "MyCustomTask1"
//val secondTask = "MyCustomTask2"
//val key = "someKey"
//val myGroup = "custom group"
//
//tasks.register(firstTask) {
//    println("$name init 🚀")
////    this.doFirst {
////        println("$name do first work 1")
////    }
//    doFirst {
//        println("$name do first work 1")
//
//        project.ext.set(key, "custom data 💿")
//    }
//    doLast {
//        println("$name do last work 3")
//    }
////    group = myGroup
//}
//
//
//tasks.configureEach {
//    if (name.contains("Custom")) {
//        group = myGroup
//    }
//}
//
//tasks.register(secondTask) {
//    println("$name init 🛵")
//
//    dependsOn(firstTask)
//
//    doFirst {
//        println("$name do first work 1")
//
//        println("1 | got data ${project.findProperty(key)}")
//
//        // no data found from gradle
//        println("2 | got data ${project.findProperty("WRONG KEY")}")
//
//        // data from properties
//        println("3 | got data ${project.findProperty("someKeyProperties")}")
//    }
////    group = myGroup
//}
//
//
////tasks.forEach { task ->
////    if (task.name.contains("Custom")) {
////        task.group = myGroup
////    }
////}
//
//
//tasks.register("Custom keks")